### ISSUE TITLE
Список

### ISSUE THREAD

**Issue by TxAnton** [JAkutenshi/spbetu_os_2020_8383#1]
| github
-- | --
Аверина Ольга Сергеевна | olyaave
Бабенко Никита Сергеевич | tabakerkaaaa
Бессуднов Глеб Ильич | GlebDot
Дейнега Виктор Евгеньевич | holyunchained
Ишанина Людмила Николаевна | MilaIshanina
Колмыков Владислав Денисович | tsvlad
Кормщикова Арина Олеговна | Pchooo
Костарев Кирилл Владимирович | kikos2359
Курбанов Тимур Амирович |  
Ларин Антон | TxAnton
Максимова Анастасия Александровна | AlexxxMaxxx
Мирсков Андрей Андреевич | MadAndrei
Мололкин Кирилл Алексеевич | Kirill-mol
Степанов Владислав Денисович | VladisStep
Сырцова Екатерина Андреевна | KaterinaSyrtsova
Тимченко Георгий Андреевич | GeorgeTim
Федоров Илья Андреевич | IlyaFedorov115
Шишкин Иван Викторович | IvanShish
Яхимович Павел Викторович | honorhunter

**Comment by JAkutenshi** [comment]
Спасибо, всех добавил
